version: "3.8"
# sudo docker-compose -f dev-docker-compose.yaml down
services:
  hschema_postgres_db:
    image: postgres:15-alpine
    container_name: hschema_postgres_db
    volumes:
      - hschema_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: storage_db
    networks:
      - pyHanaNet
networks:
  pyHanaNet:
volumes:
  hschema_postgres_data: