version: "3.8"

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_hana_server  
    #volumes:    
    # - ./api/app/:/app
    ports:
     - 8998:8000
    networks:
     - pyHanaNet

networks:
  pyHanaNet: